### ISSUE TITLE
Does not work with Ubiquity

### ISSUE THREAD

**Issue by sgmelin** [vmware/network-insight-sdk-generic-datasources#36]
Hi.
I used installed the SDK as described but the script fails. Message is:

`python ./network_insight_sdk_generic_datasources/main.py -d ubiquity -s UBIQUITI_EDGESWITCH -i 192.168.5.109 -u *** -p *** -o tor1.zip
2020-01-07 17:00:19,093:  log.py         : 46   CRITICAL: Log file Name: /tmp/third_party_sdk_7NOnaj.log
Traceback (most recent call last):
  File "./network_insight_sdk_generic_datasources/main.py", line 59, in <module>
    main()
  File "./network_insight_sdk_generic_datasources/main.py", line 41, in main
    yaml_definition_file_name)) as f:
IOError: [Errno 2] No such file or directory: './network_insight_sdk_generic_datasources/routers_and_switches/ubiquity/ubiquity.yml'`

The log file does not exist.
I use Ubuntu as OS.

Any ideas?

**Comment by smitmartijn** [comment]
Hi @sgmelin - try "ubiquiti" and not "ubiquity". Also, the available template is for edgerouter-lite, which should be given as the device type (-s)

**Comment by smitmartijn** [comment]
Closing because there's no feedback.
