### ISSUE TITLE
IndentationError: unexpected indent

### ISSUE THREAD

**Issue by Bateneira** [vmware/network-insight-sdk-generic-datasources#43]
Hello, I'm trying to execute the scripts but i'm facing an issue and don't know how to fix it :

2020-02-19 09:02:12,498:  log.py         : 46   CRITICAL: Log file Name: /tmp/third_party_sdk_ev8dl3.log
Traceback (most recent call last):
  File "./network_insight_sdk_generic_datasources/main.py", line 59, in <module>
    main()
  File "./network_insight_sdk_generic_datasources/main.py", line 32, in main
    import network_insight_sdk_generic_datasources.common.physical_device as physical_device
  File "/root/network-insight-sdk-generic-datasources/network_insight_sdk_generic_datasources/common/physical_device.py", line 7, in <module>
    from network_insight_sdk_generic_datasources.connection.ssh_connect_handler import SSHConnectHandler
  File "/root/network-insight-sdk-generic-datasources/network_insight_sdk_generic_datasources/connection/ssh_connect_handler.py", line 4, in <module>
    from netmiko import ConnectHandler
  File "/usr/local/lib/python2.7/dist-packages/netmiko/__init__.py", line 7, in <module>
    from netmiko.ssh_dispatcher import ConnectHandler
  File "/usr/local/lib/python2.7/dist-packages/netmiko/ssh_dispatcher.py", line 2, in <module>
    from netmiko.a10 import A10SSH
  File "/usr/local/lib/python2.7/dist-packages/netmiko/a10/__init__.py", line 1, in <module>
    from netmiko.a10.a10_ssh import A10SSH
  File "/usr/local/lib/python2.7/dist-packages/netmiko/a10/a10_ssh.py", line 3, in <module>
    from netmiko.cisco_base_connection import CiscoSSHConnection
  File "/usr/local/lib/python2.7/dist-packages/netmiko/cisco_base_connection.py", line 143
    msg = f"Login failed: {self.host}"
                                     ^
SyntaxError: invalid syntax

Can anyone have an idea ?

Many thanks

**Comment by smitmartijn** [comment]
Hi @Bateneira - it looks like netmiko no longer supports Python 2, and you need 3. Can you upgrade your Python version and see if that works?

**Comment by smitmartijn** [comment]
Closing because there's no feedback.
