### ISSUE TITLE
physical_device.py: 103  ERROR   : Error occurred while executing command : 'name' Traceback (most recent call last)

### ISSUE THREAD

**Issue by tmeppen** [vmware/network-insight-sdk-generic-datasources#56]
### Describe the bug

error at the end.

root@nmvrnisdk:/# python3 /usr/bin/network_insight_sdk_generic_datasources/main.py -d cisco -m n5k -s CISCO_IOS -i 192.168.230.3 -u USER -p PASSWORD -o cisco-n5k-192.168.230.3.zip
2022-11-04 15:10:49,155:  log.py         : 46   CRITICAL: Log file Name: /tmp/third_party_sdk_6cn9yz9a.log
2022-11-04 15:10:49,361:  ssh_connect_handler.py: 23   INFO    : Making connection to Device IP 192.168.230.3 Type cisco_ios
2022-11-04 15:10:49,364:  transport.py   : 1874 INFO    : Connected (version 2.0, client Cisco-1.25)
2022-11-04 15:10:49,596:  transport.py   : 1874 INFO    : 
2022-11-04 15:10:49,670:  transport.py   : 1874 INFO    : Authentication (password) successful!
2022-11-04 15:10:50,856:  physical_device.py: 85   INFO    : Processing workload {'table_id': 'switch', 'command': 'show version', 'parser': {'pre_post_processor': 'CiscoDevicePrePostProcessor', 'name': 'network_insight_sdk_generic_datasources.parsers.common.vertical_table_parser.VerticalTableParser'}}
2022-11-04 15:10:50,856:  ssh_connect_handler.py: 29   INFO    : Executing command <show version>
2022-11-04 15:10:50,964:  ssh_connect_handler.py: 31   INFO    : Cisco IOS XE Software, Version 17.05.01
Cisco IOS Software [Bengaluru], Catalyst L3 Switch Software (CAT9K_IOSXE), Version 17.5.1, RELEASE SOFTWARE (fc3)
Technical Support: http://www.cisco.com/techsupport
Copyright (c) 1986-2021 by Cisco Systems, Inc.
Compiled Wed 31-Mar-21 01:46 by mcpre

Cisco IOS-XE software, Copyright (c) 2005-2021 by cisco Systems, Inc.
All rights reserved.  Certain components of Cisco IOS-XE software are
licensed under the GNU General Public License ("GPL") Version 2.0.  The
software code licensed under GPL Version 2.0 is free software that comes
with ABSOLUTELY NO WARRANTY.  You can redistribute and/or modify such
GPL code under the terms of GPL Version 2.0.  For more details, see the
documentation or "License Notice" file accompanying the IOS-XE software,
or the applicable URL provided on the flyer accompanying the IOS-XE
software.

ROM: IOS-XE ROMMON
BOOTLDR: System Bootstrap, Version 17.5.2r, RELEASE SOFTWARE (P)

LATHM-203-SW03 uptime is 1 day, 20 hours, 37 minutes
Uptime for this control processor is 1 day, 20 hours, 39 minutes
System returned to ROM by PowerOn at 14:26:39 EST Tue Nov 1 2022
System restarted at 14:32:51 EST Wed Nov 2 2022
System image file is "flash:packages.conf"
Last reload reason: PowerOn

This product contains cryptographic features and is subject to United
States and local country laws governing import, export, transfer and
use. Delivery of Cisco cryptographic products does not imply
third-party authority to import, export, distribute or use encryption.
Importers, exporters, distributors and users are responsible for
compliance with U.S. and local country laws. By using this product you
agree to comply with applicable laws and regulations. If you are unable
to comply with U.S. and local laws, return this product immediately.

A summary of U.S. laws governing Cisco cryptographic products may be found at:
http://www.cisco.com/wwl/export/crypto/tool/stqrg.html

If you require further assistance please contact us by sending email to
export@cisco.com.

Technology Package License Information:

------------------------------------------------------------------------------
Technology-package                                     Technology-package
Current                        Type                       Next reboot
------------------------------------------------------------------------------
network-advantage       Smart License                    network-advantage
dna-advantage           Subscription Smart License       dna-advantage
AIR License Level: AIR DNA Advantage
Next reload AIR license Level: AIR DNA Advantage

Smart Licensing Status: Registration Not Applicable/Not Applicable

cisco C9300-48P (X86) processor with 1322407K/6147K bytes of memory.
Processor board ID FJC253717TZ
2 Virtual Ethernet interfaces
104 Gigabit Ethernet interfaces
16 Ten Gigabit Ethernet interfaces
4 TwentyFive Gigabit Ethernet interfaces
4 Forty Gigabit Ethernet interfaces
2048K bytes of non-volatile configuration memory.
8388608K bytes of physical memory.
1638400K bytes of Crash Files at crashinfo:.
1638400K bytes of Crash Files at crashinfo-2:.
11264000K bytes of Flash at flash:.
11264000K bytes of Flash at flash-2:.

Base Ethernet MAC Address          : 04:76:b0:75:e4:00
Motherboard Assembly Number        : 73-18274-05
Motherboard Serial Number          : FJZ24390KGU
Model Revision Number              : A0
Motherboard Revision Number        : A0
Model Number                       : C9300-48P
System Serial Number               : FJC253717TZ
CLEI Code Number                   :

Switch Ports Model              SW Version        SW Image              Mode
------ ----- -----              ----------        ----------            ----
*    1 65    C9300-48P          17.05.01          CAT9K_IOSXE           INSTALL
     2 65    C9300-48P          17.05.01          CAT9K_IOSXE           INSTALL

Switch 02
---------
Switch uptime                      : 1 day, 20 hours, 39 minutes

Base Ethernet MAC Address          : 68:9e:0b:26:02:00
Motherboard Assembly Number        : 73-18274-05
Motherboard Serial Number          : FJZ24390UV9
Model Revision Number              : A0
Motherboard Revision Number        : A0
Model Number                       : C9300-48P
System Serial Number               : FJC25341BZ4
Last reload reason                 : PowerOn
CLEI Code Number                   :

Configuration register is 0x102

2022-11-04 15:10:50,965:  physical_device.py: 96   INFO    : Command show version Result Cisco IOS XE Software, Version 17.05.01
Cisco IOS Software [Bengaluru], Catalyst L3 Switch Software (CAT9K_IOSXE), Version 17.5.1, RELEASE SOFTWARE (fc3)
Technical Support: http://www.cisco.com/techsupport
Copyright (c) 1986-2021 by Cisco Systems, Inc.
Compiled Wed 31-Mar-21 01:46 by mcpre

Cisco IOS-XE software, Copyright (c) 2005-2021 by cisco Systems, Inc.
All rights reserved.  Certain components of Cisco IOS-XE software are
licensed under the GNU General Public License ("GPL") Version 2.0.  The
software code licensed under GPL Version 2.0 is free software that comes
with ABSOLUTELY NO WARRANTY.  You can redistribute and/or modify such
GPL code under the terms of GPL Version 2.0.  For more details, see the
documentation or "License Notice" file accompanying the IOS-XE software,
or the applicable URL provided on the flyer accompanying the IOS-XE
software.

ROM: IOS-XE ROMMON
BOOTLDR: System Bootstrap, Version 17.5.2r, RELEASE SOFTWARE (P)

LATHM-203-SW03 uptime is 1 day, 20 hours, 37 minutes
Uptime for this control processor is 1 day, 20 hours, 39 minutes
System returned to ROM by PowerOn at 14:26:39 EST Tue Nov 1 2022
System restarted at 14:32:51 EST Wed Nov 2 2022
System image file is "flash:packages.conf"
Last reload reason: PowerOn

This product contains cryptographic features and is subject to United
States and local country laws governing import, export, transfer and
use. Delivery of Cisco cryptographic products does not imply
third-party authority to import, export, distribute or use encryption.
Importers, exporters, distributors and users are responsible for
compliance with U.S. and local country laws. By using this product you
agree to comply with applicable laws and regulations. If you are unable
to comply with U.S. and local laws, return this product immediately.

A summary of U.S. laws governing Cisco cryptographic products may be found at:
http://www.cisco.com/wwl/export/crypto/tool/stqrg.html

If you require further assistance please contact us by sending email to
export@cisco.com.

Technology Package License Information:

------------------------------------------------------------------------------
Technology-package                                     Technology-package
Current                        Type                       Next reboot
------------------------------------------------------------------------------
network-advantage       Smart License                    network-advantage
dna-advantage           Subscription Smart License       dna-advantage
AIR License Level: AIR DNA Advantage
Next reload AIR license Level: AIR DNA Advantage

Smart Licensing Status: Registration Not Applicable/Not Applicable

cisco C9300-48P (X86) processor with 1322407K/6147K bytes of memory.
Processor board ID FJC253717TZ
2 Virtual Ethernet interfaces
104 Gigabit Ethernet interfaces
16 Ten Gigabit Ethernet interfaces
4 TwentyFive Gigabit Ethernet interfaces
4 Forty Gigabit Ethernet interfaces
2048K bytes of non-volatile configuration memory.
8388608K bytes of physical memory.
1638400K bytes of Crash Files at crashinfo:.
1638400K bytes of Crash Files at crashinfo-2:.
11264000K bytes of Flash at flash:.
11264000K bytes of Flash at flash-2:.

Base Ethernet MAC Address          : 04:76:b0:75:e4:00
Motherboard Assembly Number        : 73-18274-05
Motherboard Serial Number          : FJZ24390KGU
Model Revision Number              : A0
Motherboard Revision Number        : A0
Model Number                       : C9300-48P
System Serial Number               : FJC253717TZ
CLEI Code Number                   :

Switch Ports Model              SW Version        SW Image              Mode
------ ----- -----              ----------        ----------            ----
*    1 65    C9300-48P          17.05.01          CAT9K_IOSXE           INSTALL
     2 65    C9300-48P          17.05.01          CAT9K_IOSXE           INSTALL

Switch 02
---------
Switch uptime                      : 1 day, 20 hours, 39 minutes

Base Ethernet MAC Address          : 68:9e:0b:26:02:00
Motherboard Assembly Number        : 73-18274-05
Motherboard Serial Number          : FJZ24390UV9
Model Revision Number              : A0
Motherboard Revision Number        : A0
Model Number                       : C9300-48P
System Serial Number               : FJC25341BZ4
Last reload reason                 : PowerOn
CLEI Code Number                   :

Configuration register is 0x102

2022-11-04 15:10:50,971:  physical_device.py: 103  ERROR   : Error occurred while executing command : 'name'
Traceback (most recent call last):
  File "/usr/bin/network_insight_sdk_generic_datasources/main.py", line 59, in <module>
    main()
  File "/usr/bin/network_insight_sdk_generic_datasources/main.py", line 52, in main
    physical_device.process()
  File "/usr/bin/network_insight_sdk_generic_datasources/common/physical_device.py", line 48, in process
    self.execute_commands()
  File "/usr/bin/network_insight_sdk_generic_datasources/common/physical_device.py", line 104, in execute_commands
    raise e
  File "/usr/bin/network_insight_sdk_generic_datasources/common/physical_device.py", line 100, in execute_commands
    table[0]['name'] = "{}-{}".format(table[0]['name'], self.credentials.ip_or_fqdn)
KeyError: 'name'

### Reproduction steps

1. I get an error when trying to run the sdk.
2.
3.
...

### Expected behavior

The sdk should produce a zip file

**Comment by piyushvm** [comment]
@tmeppen Is this Cat 9k ?
